development:
  adapter: mysql
  database: djdarby_dev
  username: root
  password:
  socket: /tmp/mysql.sock
test:
  adapter: mysql
  database: djdarby_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: djdarby_prod
  username: root
  password: 
  socket: /tmp/mysql.sock
