development:
  adapter: mysql
  database: djdarby_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: djdarby_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: djdarby_prod
  username: root
  password: 
  socket: /tmp/mysql.sock
